# Generated by Django 6.1.1 on 2026-09-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('artists', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('contact', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('canceled', 'Canceled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='accounts.managerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier3', 'Normal'), ('tier2', 'Special'), ('tier1', 'Elite'), ('tier0', 'VIP')], default='tier3', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=100)),
                ('available_quantity', models.PositiveIntegerField(default=100)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='concerts.concert')),
            ],
            options={
                'unique_together': {('concert', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='AttendeeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to='accounts.attendeeprofile')),
                ('concert_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_passes', to='concerts.concertticket')),
            ],
        ),
    ]
